#1586

diff --git a/files/muscolo.softecspa.it/bin/backup-www b/files/muscolo.softecspa.it/bin/backup-www
--- a/files/muscolo.softecspa.it/bin/backup-www
+++ b/files/muscolo.softecspa.it/bin/backup-www
@@ -50,7 +50,7 @@ if [ -e $LOCKFILE ]
 then
     echo "ERROR: already runnig..." >&2;
     #Invia un critical a nagios
-    echo -e "muscolo\tbackup_disco_usb_www\t2\tAlready running" | $NSCA -H $NAGIOS_SERVER
+    echo -e "muscolo\tbackup_disco_usb_www_clusterasp\t2\tAlready running" | $NSCA -H $NAGIOS_SERVER
     exit 1
 else
     touch $LOCKFILE
@@ -63,7 +63,7 @@ then
     then
         echo "ERROR: USB disk not mounted. Cannot mount $MOUNTPOINT..." >&2;
         #Invia un critical a nagios
-        echo -e "muscolo\tbackup_disco_usb_www\t2\tERROR: USB disk not mounted. Cannot mount $MOUNTPOINT..." | $NSCA -H $NAGIOS_SERVER
+        echo -e "muscolo\tbackup_disco_usb_www_clusterasp\t2\tERROR: USB disk not mounted. Cannot mount $MOUNTPOINT..." | $NSCA -H $NAGIOS_SERVER
         rm ${LOCKFILE}
         exit 1
     fi
@@ -102,7 +102,7 @@ case ${DAY_OF_WEEK} in
     LABEL="full"
     ;;
     *)
-        echo "ERROR: Can't match day of week" >&2; rm $LOCKFILE; echo -e "muscolo\tbackup_disco_usb_www\t2\tCan't match day of week" | $NSCA -H $NAGIOS_SERVER >/dev/null; rm $LOCKFILE; exit 1 ;;
+        echo "ERROR: Can't match day of week" >&2; rm $LOCKFILE; echo -e "muscolo\tbackup_disco_usb_www_clusterasp\t2\tCan't match day of week" | $NSCA -H $NAGIOS_SERVER >/dev/null; rm $LOCKFILE; exit 1 ;;
 esac
 
 DESTDIR="${DESTDIR}-${LABEL}"
@@ -132,7 +132,7 @@ DELETE_LOG="${DESTDIR}/delete-backup.log"
 if [ "${RETVAL}" -ne "0" ]; then
     echo "`date` - smartfind FAILED, exit code ${RETVAL}" >> ${DELETE_LOG};
     #Invia un critical a nagios
-    echo -e "muscolo\tbackup_disco_usb_www\t2\tBackup non eseguito" | $NSCA -H $NAGIOS_SERVER >/dev/null
+    echo -e "muscolo\tbackup_disco_usb_www_clusterasp\t2\tBackup non eseguito" | $NSCA -H $NAGIOS_SERVER >/dev/null
     rm $LOCKFILE
     exit 1
 fi
@@ -140,7 +140,7 @@ fi
 # 12/07/2011 Fx ticket 630 - invio un OK al check nagios. Da rivedere facendo
 # si che lo smartfind logghi diversamente gli errori e che possa essere
 # controllato se tutti i file sono stati copiati correttamente.
-echo -e "muscolo\tbackup_disco_usb_www\t0\tUltimo backup eseguito `date +%d/%m/%Y` `date +%T`" | $NSCA -H $NAGIOS_SERVER >/dev/null
+echo -e "muscolo\tbackup_disco_usb_www_clusterasp\t0\tUltimo backup eseguito `date +%d/%m/%Y` `date +%T`" | $NSCA -H $NAGIOS_SERVER >/dev/null
 
 cd ${DESTPATH} 2>/dev/null || \
     { echo "`date` - cd ${DESTPATH}: FAILED" >> ${DELETE_LOG}; rm ${LOCKFILE}; exit 1; };
